### ISSUE TITLE
Too many slimes spawn on kelakaria

### ISSUE THREAD

**Issue by daredevil28** [GingerWalnut/SQBeyondPublic#4]
https://i.imgur.com/KqgZT28.png

**Comment by GingerWalnut** [comment]
Fixed for next restart

**Comment by SomethingSomethingAllison** [comment]
Slimes are still an issue on Kel, for some reason everytime I go outdoors outside Ordenstaat base they spawn like crazy and kill me and then my faction members have to waste time killing them.
